steps:
- name: gcr.io/cloud-builders/gsutil
  id: Sync composer bucket with dags folder.
  args: ["rsync", "-r", "-d", "./airflow/dags", "gs://$_DAG_BUCKET/dags"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud composer environments update $_COMPOSER_NAME \
        --update-pypi-packages-from-file airflow/config/requirements.txt \
        --location us-east4 --verbosity=debug \
      || exit 1
  id: 'update-composer-env-requirements'
  timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY