MERGE `chicago_taxi.taxi_trips` main
USING `chicago_taxi.taxi_trips_staging` staging
ON main.unique_key = staging.unique_key
WHEN MATCHED THEN
    UPDATE SET
        main.taxi_id = staging.taxi_id,
        main.trip_start_timestamp = staging.trip_start_timestamp,
        main.trip_end_timestamp = staging.trip_end_timestamp,
        main.trip_seconds = staging.trip_seconds,
        main.trip_miles = staging.trip_miles,
        main.pickup_census_tract = staging.pickup_census_tract,
        main.dropoff_census_tract = staging.dropoff_census_tract,
        main.pickup_community_area = staging.pickup_community_area,
        main.dropoff_community_area = staging.dropoff_community_area,
        main.fare = staging.fare,
        main.tips = staging.tips,
        main.tolls = staging.tolls,
        main.extras = staging.extras,
        main.trip_total = staging.trip_total,
        main.payment_type = staging.payment_type,
        main.company = staging.company,
        main.pickup_latitude = staging.pickup_latitude,
        main.pickup_longitude = staging.pickup_longitude,
        main.pickup_location = staging.pickup_location,
        main.dropoff_latitude = staging.dropoff_latitude,
        main.dropoff_longitude = staging.dropoff_longitude,
        main.dropoff_location = staging.dropoff_location
WHEN NOT MATCHED THEN
    INSERT(
        unique_key, 
        taxi_id, 
        trip_start_timestamp, 
        trip_end_timestamp, 
        trip_seconds, 
        trip_miles, 
        pickup_census_tract, 
        dropoff_census_tract, 
        pickup_community_area, 
        dropoff_community_area, 
        fare, 
        tips, 
        tolls, 
        extras, 
        trip_total, 
        payment_type, 
        company, 
        pickup_latitude, 
        pickup_longitude, 
        pickup_location, 
        dropoff_latitude, 
        dropoff_longitude, 
        dropoff_location
    )
    VALUES(
        staging.unique_key,
        staging.taxi_id, 
        staging.trip_start_timestamp, 
        staging.trip_end_timestamp, 
        staging.trip_seconds, 
        staging.trip_miles, 
        staging.pickup_census_tract, 
        staging.dropoff_census_tract, 
        staging.pickup_community_area, 
        staging.dropoff_community_area, 
        staging.fare, 
        staging.tips, 
        staging.tolls, 
        staging.extras, 
        staging.trip_total, 
        staging.payment_type, 
        staging.company, 
        staging.pickup_latitude, 
        staging.pickup_longitude, 
        staging.pickup_location, 
        staging.dropoff_latitude, 
        staging.dropoff_longitude, 
        staging.dropoff_location
    )
    